### ISSUE TITLE
Error: ARC forbids Objective-C in...  (Added as cocoapods)

### ISSUE THREAD

**Issue by loginov** [ShareKit/ShareKit#1003] opened 2015-02-19 07:41 UTC
![screen shot 2015-02-19 at 10 40 32](https://cloud.githubusercontent.com/assets/2863775/6263177/c5a82064-b823-11e4-8e32-f6f3fd33697a.png)

**Comment by VilemKurz** [comment] 2015-02-19 08:51
duplicate of #996. Use search and update cocoa pods.

**Closed by VilemKurz** 2015-02-19 08:51 UTC

**Comment by loginov** [comment] 2015-02-19 09:21
>>Using ShareKit (4.0.3)
Same error
